import streamlit as st
import numpy as np
import pandas as pd
import requests
from pathlib import Path

API_URL = "http://127.0.0.1:8000/predict"

st.set_page_config(page_title="Internal Fraud Scoring Engine", layout="wide")

st.title("💳 Internal Fraud Scoring Engine")

st.info(
    "This UI acts as a frontend to a FastAPI-based fraud inference service. "
    "All predictions are generated by the backend model."
)

# ---------- Sidebar ----------
with st.sidebar:
    threshold = st.slider(
        "Fraud Probability Threshold",
        min_value=0.0,
        max_value=1.0,
        value=0.5,
        step=0.01
    )

    mode = st.radio(
        "Input Mode",
        [
            "Manual Latent Feature Input",
            "Random Transaction (Demo)",
            "Upload PCA-Transformed CSV"
        ]
    )

# ---------- Load dataset for demo ----------
data_path = Path(__file__).resolve().parents[1] / "creditcard.csv"

X = None
source = ""

NUM_FEATURES = 30  # known from dataset

# ---------- Input modes ----------
if mode == "Manual Latent Feature Input":
    st.subheader("Manual Latent Feature Input")

    cols = st.columns(3)
    vals = []

    for i in range(NUM_FEATURES):
        col = cols[i % 3]
        vals.append(
            col.number_input(
                f"Latent Feature {i+1}",
                value=0.0,
                format="%.6f"
            )
        )

    X = np.array(vals).reshape(1, -1)
    source = "Manual input"

elif mode == "Random Transaction (Demo)":
    st.subheader("Random Transaction Demo")

    if data_path.exists():
        df = pd.read_csv(data_path).drop(columns=["Class"])
        sample = df.sample(1)
        X = sample.values
        source = "Random dataset sample"
        st.dataframe(sample)
    else:
        st.error("creditcard.csv not found.")

elif mode == "Upload PCA-Transformed CSV":
    st.subheader("Upload PCA-Transformed CSV")

    file = st.file_uploader("Upload CSV", type=["csv"])
    if file:
        df = pd.read_csv(file)
        if df.shape[1] != NUM_FEATURES:
            st.error(f"Expected {NUM_FEATURES} columns.")
        else:
            X = df.values
            source = "Uploaded CSV"
            st.dataframe(df.head())

# ---------- Call API ----------
if X is not None and st.button("🚨 Score Fraud Risk"):
    payload = {
        "features": X.tolist(),
        "threshold": threshold
    }

    try:
        response = requests.post(API_URL, json=payload)
        response.raise_for_status()
        result = response.json()

        results_df = pd.DataFrame({
            "Fraud Probability": result["fraud_probability"],
            "Prediction": [
                "FRAUD" if p == 1 else "LEGIT"
                for p in result["prediction"]
            ]
        })

        st.subheader("📊 Results")
        st.caption(f"Source: {source} | Threshold = {threshold}")
        st.dataframe(results_df)

        st.metric(
            "Flagged as Fraud (%)",
            f"{100 * np.mean(result['prediction']):.2f}%"
        )

    except Exception as e:
        st.error(f"API error: {e}")
